# Generated by Django 2.1.7 on 2019-03-15 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='date_posted',
            new_name='creation_date',
        ),
    ]
